config/routes.rb
Rails.application.routes.draw do
  resources :pesquisa_models
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pesquisa_model.rb
class PesquisaModel < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pesquisa_models_controller.rb
class PesquisaModelsController < ApplicationController
  before_action :set_pesquisa_model, only: [:show, :edit, :update, :destroy]

  # GET /pesquisa_models
  # GET /pesquisa_models.json
  def index
    @pesquisa_models = PesquisaModel.all
  end

  # GET /pesquisa_models/1
  # GET /pesquisa_models/1.json
  def show
  end

  # GET /pesquisa_models/new
  def new
    @pesquisa_model = PesquisaModel.new
  end

  # GET /pesquisa_models/1/edit
  def edit
  end

  # POST /pesquisa_models
  # POST /pesquisa_models.json
  def create
    @pesquisa_model = PesquisaModel.new(pesquisa_model_params)

    respond_to do |format|
      if @pesquisa_model.save
        format.html { redirect_to @pesquisa_model, notice: 'Pesquisa model was successfully created.' }
        format.json { render :show, status: :created, location: @pesquisa_model }
      else
        format.html { render :new }
        format.json { render json: @pesquisa_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pesquisa_models/1
  # PATCH/PUT /pesquisa_models/1.json
  def update
    respond_to do |format|
      if @pesquisa_model.update(pesquisa_model_params)
        format.html { redirect_to @pesquisa_model, notice: 'Pesquisa model was successfully updated.' }
        format.json { render :show, status: :ok, location: @pesquisa_model }
      else
        format.html { render :edit }
        format.json { render json: @pesquisa_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pesquisa_models/1
  # DELETE /pesquisa_models/1.json
  def destroy
    @pesquisa_model.destroy
    respond_to do |format|
      format.html { redirect_to pesquisa_models_url, notice: 'Pesquisa model was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pesquisa_model
      @pesquisa_model = PesquisaModel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pesquisa_model_params
      params.require(:pesquisa_model).permit(:titulo, :descricao, :publico_alvo, :data_limite, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pesquisa_models_helper.rb
module PesquisaModelsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Easysearch</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pesquisa_models/_form.html.erb
<%= form_with(model: pesquisa_model, local: true) do |form| %>
  <% if pesquisa_model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pesquisa_model.errors.count, "error") %> prohibited this pesquisa_model from being saved:</h2>

      <ul>
      <% pesquisa_model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo, id: :pesquisa_model_titulo %>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_area :descricao, id: :pesquisa_model_descricao %>
  </div>

  <div class="field">
    <%= form.label :publico_alvo %>
    <%= form.text_field :publico_alvo, id: :pesquisa_model_publico_alvo %>
  </div>

  <div class="field">
    <%= form.label :data_limite %>
    <%= form.date_select :data_limite, id: :pesquisa_model_data_limite %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link, id: :pesquisa_model_link %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pesquisa_models/edit.html.erb
<h1>Editing Pesquisa Model</h1>

<%= render 'form', pesquisa_model: @pesquisa_model %>

<%= link_to 'Show', @pesquisa_model %> |
<%= link_to 'Back', pesquisa_models_path %>

app/views/pesquisa_models/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pesquisa Models</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Descrição</th>
      <th>Publico alvo</th>
      <th>Data limite</th>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pesquisa_models.each do |pesquisa_model| %>
      <tr>
        <td><%= pesquisa_model.titulo %></td>
        <td><%= pesquisa_model.descricao %></td>
        <td><%= pesquisa_model.publico_alvo %></td>
        <td><%= pesquisa_model.data_limite %></td>
        <td><%= pesquisa_model.link %></td>
        <td><%= link_to 'Show', pesquisa_model %></td>
        <td><%= link_to 'Edit', edit_pesquisa_model_path(pesquisa_model) %></td>
        <td><%= link_to 'Destroy', pesquisa_model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pesquisa Model', new_pesquisa_model_path %>

app/views/pesquisa_models/new.html.erb
<h1>New Pesquisa Model</h1>

<%= render 'form', pesquisa_model: @pesquisa_model %>

<%= link_to 'Back', pesquisa_models_path %>

app/views/pesquisa_models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @pesquisa_model.titulo %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @pesquisa_model.descricao %>
</p>

<p>
  <strong>Publico alvo:</strong>
  <%= @pesquisa_model.publico_alvo %>
</p>

<p>
  <strong>Data limite:</strong>
  <%= @pesquisa_model.data_limite %>
</p>

<p>
  <strong>Link:</strong>
  <%= @pesquisa_model.link %>
</p>

<%= link_to 'Edit', edit_pesquisa_model_path(@pesquisa_model) %> |
<%= link_to 'Back', pesquisa_models_path %>